baseURL: http://velanms.com
languageCode: en-us
title: Velan Salis.
theme: papermod

params:
  ShowFullTextinRSS: true
  defaultTheme: dark
  disableThemeToggle: true
  ShowToc: true
  DateFormat: "January 2, 2006"
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  
  socialIcons:
    - name: "gitea"
      url: "https://codeberg.org/velanms"
    - name: "email"
      url: "mailto:mail@velanms.com"
    - name: "mastodon"
      url: "https://fosstodon.org/@velanms"
    - name: "linkedin"
      url: "https://linkedin.com/in/velansalis"


  profileMode:
    enabled: true
    title: Hey There! 👋
    subtitle: I'm just another developer, trying new things, making
      stupid mistakes and learning from them! Welcome to my little corner of the
      internet.
    imageUrl: https://cdn.fosstodon.org/accounts/avatars/111/799/778/793/216/769/original/c24cb515cc4aa070.png
    imageTitle: Velan
    imageWidth: 120
    imageHeight: 120

menu:
  main:
    - name: Posts
      url: /posts
      weight: 1
      permlink: /posts
      slug: posts
    - name: Elsewhere
      url: /elsewhere
      weight: 2
      permlink: /elsewhere
      slug: elsewhere
    - name: Uses
      url: /uses
      weight: 3
      permlink: /uses
      slug: uses

outputs:
  home:
    - HTML
    - RSS
    - JSON
