baseURL: https://velanms.com/
languageCode: en-us
title: Velan Salis.
theme: papermod

params:
  ShowFullTextinRSS: true
  defaultTheme: dark
  disableThemeToggle: true
  ShowToc: true
  DateFormat: "January 2, 2006"
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  
  socialIcons:
    - name: "gitea"
      url: "https://codeberg.org/velanms"
    # - name: "github"
    #   url: "https://github.com/0xv31an5a1i5"
    # - name: "keybase"
    #   url: "https://keyoxide.org/hkp/hi%400xv31an5a1i5.xyz"
    - name: "email"
      url: "mailto:mail@velanms.com"
    - name: "mastodon"
      url: "https://fosstodon.org/@velanms"
    # - name: "matrix"
    #   url: "https://matrix.to/#/@0xv31an5a1i5:chat.lhin.space"
    # - name: "telegram"
    #   url: "https://t.me/velansalis"

  profileMode:
    enabled: true
    title: Hey There! 👋
    subtitle: I'm just another developer, trying new things, making
      stupid mistakes and learning from them! Welcome to my little corner of the
      internet.
    imageUrl: https://media.licdn.com/dms/image/D5603AQGTkh2zsBW1lw/profile-displayphoto-shrink_200_200/0/1688693465899?e=2147483647&v=beta&t=bfhd8R6Pd4DuYbWI4zJ--l1pFBKY9RXjEx5J23pYw1I
    imageTitle: Velan
    imageWidth: 120
    imageHeight: 120

menu:
  main:
    - name: Posts
      url: /posts
      weight: 1
      permlink: /posts
      slug: posts
    - name: Elsewhere
      url: /elsewhere
      weight: 2
      permlink: /elsewhere
      slug: elsewhere
    - name: Uses
      url: /uses
      weight: 3
      permlink: /uses
      slug: uses

outputs:
  home:
    - HTML
    - RSS
    - JSON
