baseURL = 'https://0xv31an5a1i5.xyz/'
languageCode = 'en-us'
title = 'Velan Salis'
theme = 'papermod'

[params.profileMode]
enabled = true
title = "Velan Salis"
subtitle = "Just another developer, trying new things, making stupid mistakes and learning from them! Welcome to my little corner of the internet."
imageUrl = "<image link>"
imageTitle = "dayum!"
imageWidth = 120
imageHeight = 120
