
baseURL = 'https://0xv31an5a1i5.xyz/'
languageCode = 'en-us'
title = 'Velan Salis'
theme = 'papermod'

[params.profileMode]
enabled = true
title = "Hey There! 👋"
subtitle = "Velan here! I'm just another developer, trying new things, making stupid mistakes and learning from them! Welcome to my little corner of the internet."
imageUrl = "https://codeberg.org/avatars/fd0901cdcb80439bc8849901838965f0?size=1160"
imageTitle = "Velan"
imageWidth = 120
imageHeight = 120
defaultTheme = "dark"
disableThemeToggle = true
ShowToc = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1
    permlink = "/posts"
    slug = "posts"
  [[menu.main]]
    name = "Archive"
    url = "/archive"
    weight = 2
    permlink = "/archive"
    slug = "archive"
  [[menu.main]]
    name = "Search"
    url = "/search"
    weight = 3
    permlink = "/search"
    slug = "search"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

